"""empty message

Revision ID: e766f638a302
Revises: 1553eff9bb24
Create Date: 2023-05-03 10:14:25.041466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e766f638a302'
down_revision = '1553eff9bb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.drop_column('is_ai_generated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_generated', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
